name: Deploy no Kubernetes

on:
  workflow_call:
    inputs:
      manifests:
        type: string
        required: true
        description: "Arquivos de manifesto para deploy"

      images:
        type: string
        required: true
        description: "Imagens que serão alteradas nos manifestos"

      environment:
        type: string
        required: true
        description: "Nome do ambiente que será utilizado"

jobs:
  deploy-k8s:
    name: Deploy no Amazon EKS
    runs-on: ubuntu-latest

    # Seleciona homologacao ou producao
    environment: ${{ inputs.environment }}

    steps:

      # Baixa os arquivos do repositório
      - name: Obtendo o código
        uses: actions/checkout@v4

      # Usa as credenciais AWS do Environment selecionado
      - name: Configurando credenciais AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Mostra qual usuário AWS está sendo utilizado
      - name: Verificando identidade AWS
        run: aws sts get-caller-identity

      # Usa o kubeconfig do Environment selecionado
      - name: Configurando contexto do Kubernetes
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      # Testa o acesso ao cluster
      - name: Testando acesso ao Kubernetes
        run: |
          echo "Environment:"
          echo "${{ inputs.environment }}"

          echo "Namespace:"
          echo "${{ vars.APP_NAMESPACE }}"

          echo "Contexto atual:"
          kubectl config current-context

          echo "Nós do cluster:"
          kubectl get nodes

          echo "Pods do namespace:"
          kubectl get pods \
            --namespace "${{ vars.APP_NAMESPACE }}"

      # Faz o deploy
      - name: Executando o manifesto Kubernetes
        uses: Azure/k8s-deploy@v7
        with:
          manifests: ${{ inputs.manifests }}
          images: ${{ inputs.images }}
          namespace: ${{ vars.APP_NAMESPACE }}