name: CI-CD

on:
  push:

  workflow_dispatch:

permissions:
  contents: read

jobs:

  # ==========================================
  # CI - BUILD E ENVIO DA IMAGEM
  # ==========================================
 CI:
    name: Build da imagem Docker
    runs-on: ubuntu-latest

    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v7
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            lucascardoso1/aula-primeira-pipeline:v${{ github.run_number }}
            lucascardoso1/aula-primeira-pipeline:latest

  # ==========================================
  # CD - HOMOLOGAÇÃO
  # ==========================================
  CD-Homolog:
    name: Deploy em Homologação
    needs: [CI]

    uses: ./.github/workflows/deploy.yaml

    with:
      manifests: ./k8s/deployment.yaml
      images: lucascardoso1/aula-primeira-pipeline:v${{ github.run_number }}
      environment: homologacao

 # ==========================================
  # CD - Teste-Ambiente
  # ==========================================
  Teste-Ambiente:
    name: Deploy em Produção
    runs-on: ubuntu-latest
    needs: [CD-Homolog]
    environment: homologacao
    steps:
      - name: "Fake teste"
        run: "Fake teste de ambiente ${{ $vars.APP_NAMESPACE }}"


  # ==========================================
  # CD - PRODUÇÃO
  # ==========================================
   CD-Producao:
    name: Deploy em Produção
    needs: [CD-Homolog]

    uses: ./.github/workflows/deploy.yaml@main

    with:
      manifests: ./k8s/deployment.yaml
      images: lucascardoso1/aula-primeira-pipeline:v${{ github.run_number }}
      environment: producao


